language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
sudo: false
script:
  - "npm run test"
after_script:
  - "npm install codecov &&  ./node_modules/codecov/bin/codecov && rm -rf ./coverage"
